package com.kamilkuk.food_and_recipes.model;

public enum CousineRegion {
    BRITISH, AMERICAN, CANADIAN, CHINESE, DUTCH, EGYPTIAN, FRENCH, GREEK, INDIAN, IRISH,
    ITALIAN, JAMAICAN, JAPANESE, KENYAN, MALAYSIAN, MEXICAN, MOROCCAN, POLISH, PORTUGUESE,
    RUSSIAN, SPANISH, THAI, TUNISIAN, TURKISH, VIETNAMESE, UNKNOWN
}
